### ISSUE TITLE
Livraison labo1 - impossible de valider l'exécution de votre jar sur AWS

### ISSUE THREAD

**Issue by NicolasGlassey** [AMT-Groupe02/dataobject#22]
@LucaCoduriV  @chloefont 

Chloé, Luca,

Il m'est impossible de lancer/valider votre livrable sur AWS.

![image](https://user-images.githubusercontent.com/5616312/204302681-c6760706-47a9-4493-9742-af60a9411a77.png)

Avez-vous bien validé cette partie du labo ?
A demain

**Comment by LucaCoduriV** [comment]
Le programme fonctionnait sur aws quand nous l'avions testé.
Avez-vous bien suivi notre Readme ? Il ne faut pas oublier d'indiquer les credentials avant d'exécuter le programme.
Sinon, nous pouvons regarder cela ensemble demain.

**Comment by NicolasGlassey** [comment]
@LucaCoduriV  @chloefont 

Je viens de valider votre livrable sur AWS.

On est bien d'accord, ce fonctionnement en déclarant des variables temporaires doit être abandonné, pour soit:
* utiliser des variables d'environnement persistentes
* utiilser un fichier de config

Dans un cas comme l'autre, le client ne doit pas avoir besoin de saisir les credentials à chaque appel (ou chaque session d'appel) et ils vous faut suivre les bonnes pratiques que nous avions vu en classe.

https://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/credentials.html
